// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.0
// source: strat.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Strategy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid  string                 `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Name    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mq      string                 `protobuf:"bytes,3,opt,name=mq,proto3" json:"mq,omitempty"`
	Ex      string                 `protobuf:"bytes,4,opt,name=ex,proto3" json:"ex,omitempty"`
	Created *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *Strategy) Reset() {
	*x = Strategy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Strategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Strategy) ProtoMessage() {}

func (x *Strategy) ProtoReflect() protoreflect.Message {
	mi := &file_strat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Strategy.ProtoReflect.Descriptor instead.
func (*Strategy) Descriptor() ([]byte, []int) {
	return file_strat_proto_rawDescGZIP(), []int{0}
}

func (x *Strategy) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *Strategy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Strategy) GetMq() string {
	if x != nil {
		return x.Mq
	}
	return ""
}

func (x *Strategy) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

func (x *Strategy) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

type SyncStrat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Objectid string                 `protobuf:"bytes,1,opt,name=objectid,proto3" json:"objectid,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ex       string                 `protobuf:"bytes,4,opt,name=ex,proto3" json:"ex,omitempty"`
	Created  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *SyncStrat) Reset() {
	*x = SyncStrat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncStrat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStrat) ProtoMessage() {}

func (x *SyncStrat) ProtoReflect() protoreflect.Message {
	mi := &file_strat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStrat.ProtoReflect.Descriptor instead.
func (*SyncStrat) Descriptor() ([]byte, []int) {
	return file_strat_proto_rawDescGZIP(), []int{1}
}

func (x *SyncStrat) GetObjectid() string {
	if x != nil {
		return x.Objectid
	}
	return ""
}

func (x *SyncStrat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SyncStrat) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

func (x *SyncStrat) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

// return all strats
type ReturnAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReturnAllReq) Reset() {
	*x = ReturnAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnAllReq) ProtoMessage() {}

func (x *ReturnAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_strat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnAllReq.ProtoReflect.Descriptor instead.
func (*ReturnAllReq) Descriptor() ([]byte, []int) {
	return file_strat_proto_rawDescGZIP(), []int{2}
}

type ReturnAllRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Strategy *Strategy `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`
}

func (x *ReturnAllRes) Reset() {
	*x = ReturnAllRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnAllRes) ProtoMessage() {}

func (x *ReturnAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_strat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnAllRes.ProtoReflect.Descriptor instead.
func (*ReturnAllRes) Descriptor() ([]byte, []int) {
	return file_strat_proto_rawDescGZIP(), []int{3}
}

func (x *ReturnAllRes) GetStrategy() *Strategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

// return single strat
type ReturnStratReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ReturnStratReq) Reset() {
	*x = ReturnStratReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnStratReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnStratReq) ProtoMessage() {}

func (x *ReturnStratReq) ProtoReflect() protoreflect.Message {
	mi := &file_strat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnStratReq.ProtoReflect.Descriptor instead.
func (*ReturnStratReq) Descriptor() ([]byte, []int) {
	return file_strat_proto_rawDescGZIP(), []int{4}
}

func (x *ReturnStratReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReturnStratRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Strategy *Strategy `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`
}

func (x *ReturnStratRes) Reset() {
	*x = ReturnStratRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnStratRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnStratRes) ProtoMessage() {}

func (x *ReturnStratRes) ProtoReflect() protoreflect.Message {
	mi := &file_strat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnStratRes.ProtoReflect.Descriptor instead.
func (*ReturnStratRes) Descriptor() ([]byte, []int) {
	return file_strat_proto_rawDescGZIP(), []int{5}
}

func (x *ReturnStratRes) GetStrategy() *Strategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

// create strat
type StoreStratReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Strategy *Strategy `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`
}

func (x *StoreStratReq) Reset() {
	*x = StoreStratReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreStratReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreStratReq) ProtoMessage() {}

func (x *StoreStratReq) ProtoReflect() protoreflect.Message {
	mi := &file_strat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreStratReq.ProtoReflect.Descriptor instead.
func (*StoreStratReq) Descriptor() ([]byte, []int) {
	return file_strat_proto_rawDescGZIP(), []int{6}
}

func (x *StoreStratReq) GetStrategy() *Strategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

type StoreStratRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Strategy *Strategy `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`
}

func (x *StoreStratRes) Reset() {
	*x = StoreStratRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strat_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreStratRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreStratRes) ProtoMessage() {}

func (x *StoreStratRes) ProtoReflect() protoreflect.Message {
	mi := &file_strat_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreStratRes.ProtoReflect.Descriptor instead.
func (*StoreStratRes) Descriptor() ([]byte, []int) {
	return file_strat_proto_rawDescGZIP(), []int{7}
}

func (x *StoreStratRes) GetStrategy() *Strategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

var File_strat_proto protoreflect.FileDescriptor

var file_strat_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x74, 0x72, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x08, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65,
	0x67, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x6d, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6d, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x65, 0x78, 0x12, 0x34,
	0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x09, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x74, 0x72,
	0x61, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x65, 0x78, 0x12, 0x34, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x74, 0x75,
	0x72, 0x6e, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x22, 0x3b, 0x0a, 0x0c, 0x52, 0x65, 0x74, 0x75,
	0x72, 0x6e, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x65, 0x67, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x52, 0x08, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x22, 0x24, 0x0a, 0x0e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x53,
	0x74, 0x72, 0x61, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x0e, 0x52,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a,
	0x08, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79,
	0x52, 0x08, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x22, 0x3c, 0x0a, 0x0d, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x53, 0x74, 0x72, 0x61, 0x74, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x08, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x52, 0x08,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x22, 0x3c, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x53, 0x74, 0x72, 0x61, 0x74, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x52, 0x08, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x32, 0xbe, 0x01, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x61, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x09, 0x72, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x41, 0x6c, 0x6c, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x30, 0x01,
	0x12, 0x3b, 0x0a, 0x0b, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x12,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x53, 0x74,
	0x72, 0x61, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x52, 0x65, 0x73, 0x12, 0x38, 0x0a,
	0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x74, 0x72, 0x61, 0x74, 0x12, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x74, 0x72, 0x61, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53,
	0x74, 0x72, 0x61, 0x74, 0x52, 0x65, 0x73, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_strat_proto_rawDescOnce sync.Once
	file_strat_proto_rawDescData = file_strat_proto_rawDesc
)

func file_strat_proto_rawDescGZIP() []byte {
	file_strat_proto_rawDescOnce.Do(func() {
		file_strat_proto_rawDescData = protoimpl.X.CompressGZIP(file_strat_proto_rawDescData)
	})
	return file_strat_proto_rawDescData
}

var file_strat_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_strat_proto_goTypes = []interface{}{
	(*Strategy)(nil),              // 0: proto.Strategy
	(*SyncStrat)(nil),             // 1: proto.SyncStrat
	(*ReturnAllReq)(nil),          // 2: proto.ReturnAllReq
	(*ReturnAllRes)(nil),          // 3: proto.ReturnAllRes
	(*ReturnStratReq)(nil),        // 4: proto.ReturnStratReq
	(*ReturnStratRes)(nil),        // 5: proto.ReturnStratRes
	(*StoreStratReq)(nil),         // 6: proto.StoreStratReq
	(*StoreStratRes)(nil),         // 7: proto.StoreStratRes
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_strat_proto_depIdxs = []int32{
	8, // 0: proto.Strategy.created:type_name -> google.protobuf.Timestamp
	8, // 1: proto.SyncStrat.created:type_name -> google.protobuf.Timestamp
	0, // 2: proto.ReturnAllRes.strategy:type_name -> proto.Strategy
	0, // 3: proto.ReturnStratRes.strategy:type_name -> proto.Strategy
	0, // 4: proto.StoreStratReq.strategy:type_name -> proto.Strategy
	0, // 5: proto.StoreStratRes.strategy:type_name -> proto.Strategy
	2, // 6: proto.StratService.returnAll:input_type -> proto.ReturnAllReq
	4, // 7: proto.StratService.returnStrat:input_type -> proto.ReturnStratReq
	6, // 8: proto.StratService.storeStrat:input_type -> proto.StoreStratReq
	3, // 9: proto.StratService.returnAll:output_type -> proto.ReturnAllRes
	5, // 10: proto.StratService.returnStrat:output_type -> proto.ReturnStratRes
	7, // 11: proto.StratService.storeStrat:output_type -> proto.StoreStratRes
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_strat_proto_init() }
func file_strat_proto_init() {
	if File_strat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_strat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Strategy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncStrat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnAllRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnStratReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnStratRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreStratReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strat_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreStratRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_strat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_strat_proto_goTypes,
		DependencyIndexes: file_strat_proto_depIdxs,
		MessageInfos:      file_strat_proto_msgTypes,
	}.Build()
	File_strat_proto = out.File
	file_strat_proto_rawDesc = nil
	file_strat_proto_goTypes = nil
	file_strat_proto_depIdxs = nil
}
